# Generated by Django 5.0 on 2024-06-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0002_populate_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forensic.instructiongroup'),
        ),
    ]
