# Generated by Django 5.0 on 2024-06-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0003_instructiongroup_instruction_instruction_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='forensic.instruction'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='forensic.collection'),
        ),
    ]
